### ISSUE TITLE
Feature request: trim off the trailling end of line

### ISSUE THREAD

**Issue by jonasmalacofilho** [bendmorris/hxgit#1]
I think it makes sense to remove the trialling end of line automatically, so that the `git` field behaves more like other regular data.

Essentially, this makes it a bit more direct to concatenate it with some contextual text: `return 'built from $git'` instead of `return 'built from ${StringTools.rtrim(git)}'`.

**Comment by bendmorris** [comment]
Totally agree. Done. https://github.com/bendmorris/hxgit/commit/e2a620d4adb45bf79fab361be855461a8829e02b
